import React from 'react';
import LegalPageLayout from '@/components/LegalPageLayout';

const AboutUsPage = () => {
  return (
    <LegalPageLayout title="About Us – AstroVedic AI">
      <h3 className="text-xl font-bold text-white mt-8 mb-4">🌟 Who We Are</h3>
      <p>
        Welcome to <strong>AstroVedic AI</strong>, where the timeless wisdom of Vedic astrology meets the precision of modern artificial intelligence. We are a digital platform built with a single purpose: to make authentic, personalized, and instantly accessible astrological insights available to everyone, anytime, anywhere.
      </p>

      <h3 className="text-xl font-bold text-white mt-8 mb-4">🎯 Our Mission</h3>
      <p>
        Our mission is to bridge ancient Vedic knowledge with cutting-edge technology. We aim to deliver accurate, structured, and ethically generated horoscopes, Kundlis, planetary analyses, and astrological guidance through advanced AI algorithms, ensuring that traditional wisdom remains relevant, accessible, and easy to understand in the digital age.
      </p>

      <h3 className="text-xl font-bold text-white mt-8 mb-4">🔮 What We Do</h3>
      <p>
        AstroVedic AI leverages deep learning models trained on centuries-old Vedic scriptures, mathematical astronomy, and authentic astrological principles to generate:
      </p>
      <ul className="list-disc pl-6 mt-4 space-y-2">
        <li>Detailed Birth Chart (Kundli) analyses</li>
        <li>Daily, Weekly & Monthly Horoscopes</li>
        <li>Planetary Dasha & Transit Insights</li>
        <li>Compatibility & Relationship Readings</li>
        <li>Career, Health & Finance Trend Analyses</li>
      </ul>
      <p className="mt-4">
        All content is dynamically generated by our AI engine, cross-referencing planetary positions, yogas, and Vedic mathematical frameworks to deliver consistent, objective, and personalized insights.
      </p>

      <h3 className="text-xl font-bold text-white mt-8 mb-4">✅ Why Choose AstroVedic AI</h3>
      <ul className="list-disc pl-6 mt-4 space-y-2">
        <li><strong>100% AI-Powered & Instant:</strong> Get detailed astrological reports in seconds, without waiting for manual consultations.</li>
        <li><strong>Rooted in Vedic Tradition:</strong> Algorithms trained on authentic Parashari, Jaimini, and Nadi principles.</li>
        <li><strong>Privacy-First Approach:</strong> Your birth details and personal data are encrypted, securely stored, and never shared with third parties.</li>
        <li><strong>Transparent & Ethical:</strong> Clear disclaimers, no hidden charges, no guaranteed outcomes, and full respect for your free will.</li>
        <li><strong>Always Available:</strong> Access your insights 24/7 from any device, anywhere in the world.</li>
      </ul>

      <h3 className="text-xl font-bold text-white mt-8 mb-4">⚙️ How It Works</h3>
      <p>
        Simply enter your birth details, and our AI engine instantly calculates planetary positions, dashas, transits, and yogas. The system then generates a comprehensive, easy-to-read report tailored specifically to your birth chart. All interpretations are structured, objective, and designed for self-reflection and informed decision-making.
      </p>

      <h3 className="text-xl font-bold text-white mt-8 mb-4">🤝 Our Commitment</h3>
      <p>
        We believe astrology should be a tool for awareness, not dependency. AstroVedic AI is built on the principle of responsible guidance. We do not claim to predict the future with certainty, nor do we replace professional advice. Our platform is designed to empower you with insights, helping you navigate life’s decisions with clarity, confidence, and self-awareness.
      </p>

      <div className="mt-8 p-4 bg-[#2D1B69]/30 border border-[#2D1B69] rounded-lg">
        <h3 className="text-lg font-bold text-white mb-2">⚠️ Important Note</h3>
        <p className="text-sm">
          AstroVedic AI provides content strictly for <strong>informational, educational, and entertainment purposes</strong>. Our AI-generated insights are <strong>not a substitute</strong> for professional medical, legal, financial, or psychological advice. We do not guarantee specific outcomes, and all interpretations should be used alongside personal judgment and expert guidance. If you are experiencing a mental health crisis or emergency, please contact appropriate professional helplines immediately.
        </p>
      </div>

      <h3 className="text-xl font-bold text-white mt-8 mb-4">📩 Contact Us</h3>
      <p>
        For support, queries, feedback, or partnership inquiries, you can reach us at:<br/>
        <a href="mailto:astrovedicaiii@gmail.com" className="text-[#F5C842] hover:underline font-bold mt-2 inline-block">astrovedicaiii@gmail.com</a>
      </p>

      <hr className="border-[#2D1B69] my-8" />

      <p className="italic text-zinc-400 text-center">
        Thank you for choosing AstroVedic AI. May your journey through the stars be insightful, empowering, and aligned with your highest good.
      </p>
    </LegalPageLayout>
  );
};

export default AboutUsPage;
